server:
  port: 9002

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    metadata-map:
      version: "v1.0.0"

logging:
  level:
    cn:
      com:
        yusys:
          lbswitch: debug
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG
zuul:
  routes:
    service-a:
      path: /system-a/domain1/**
      stripPrefix: true
      serviceId: service-a
    service-a2:
      path: /system-a/domain2/**
      stripPrefix: true
      serviceId: service-a
    service-b:
      path: /system-b/domain1/**
      stripPrefix: true
      serviceId: service-b