server:
  port: 9002

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 11 # 刷新到本地服务注册表中
  instance:
    metadata-map:
      version: "v1.0.0"

logging:
  level:
    cn:
      com:
        yusys:
          lbswitch: debug
    com:
      netflix:
        discovery:
          DiscoveryClient: debug
#    org:
#      springframework:
#        web:
#          servlet:
#            DispatcherServlet: DEBUG