server:
  port: 9002

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    metadata-map:
      version: "v1.0.0"

logging:
  level:
    cn:
      com:
        yusys:
          lbswitch: debug
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG