spring:
  application:
    name: spring-boot-demo
server:
  port: 9004

yusp:
  security:
    headers:
      xss: abc
      hsts:
      csrf: /tests,/users
      content-type-options: 1
      csp:
      feature-policy:
      frame-options:
      referrer-policy:
      cache-control:

    sql-injection:
      enabled: true
      regex: