spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
server:
  port: 80

management:
  endpoints:
    web:
      exposure:
        include: gateway

eureka:
  instance:
    metadata-map:
      version: "Greenwich.SR1"
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/