server:
  port: 8761

eureka:
  instance:
    metadata-map:
      version: "Finchley.SR4"
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0