spring:
  application:
    name: service-a

server:
  port: 9001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    metadata-map:
      version: "v1.0"
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${server.port}