spring:
  application:
    name: service-a
  zipkin:
    base-url: http://localhost:9411
    locator:
      discovery:
        enabled: true

server:
  port: 9001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    metadata-map:
      version: "v1.0"
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${server.port}

logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG
        cloud:
          sleuth: DEBUG

customers:
  routes: {system-a/domain1: service-a,system-b/domain1: service-b}


