server:
  port: 9011

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    metadata-map:
      version: "v1.0.0"

logging:
  level:
    org.springframework.data.r2dbc: DEBUG

spring:
  application:
    name: service-b