spring:
  application:
    name: polyglot-sidecar

server:
  port: 3001

sidecar:
  port: 3000
  health-uri: http://localhost:3000/health.json

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    metadata-map:
      version: "v1.0"
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${server.port}

logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG
        cloud:
          sleuth: DEBUG
