spring:
  application:
    name: gateway-zuul
server:
  port: 80

zuul:
  routes:
    service-a:
      path: /system-a/domain1/**
      stripPrefix: true
      serviceId: service-a
    service-a2:
      path: /system-a/domain2/**
      stripPrefix: true
      serviceId: service-a
    service-b:
      path: /system-b/domain1/**
      stripPrefix: true
      serviceId: service-b
  host:
    maxTotalConnections: 200
    maxPerRouteConnections: 20

eureka:
  instance:
    metadata-map:
      version: "Greenwich.SR1"
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/