spring:
  application:
    name: gateway-zuul
server:
  port: 80

zuul:
  host:
    maxTotalConnections: 200
    maxPerRouteConnections: 20

eureka:
  instance:
    metadata-map:
      version: "Greenwich.SR1"
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/