spring:
  application:
    name: tracing-messageing
  rabbitmq:
    host: 192.168.251.157
    port: 5673
    username: admin
    password: admin
  sleuth:
    sampler:
      probability: 1
  cloud:
    stream:
      bindings:
        input:
          destination: gs-topic
        output:
          destination: gs-topic
#logging.level.org.springframework.web: DEBUG